kind: pipeline
type: docker
name: ci/cd
volumes:
  - name: node_modules
    host:
      path: /root/drone/node-zzf/node_modules
  - name: next_cache
    host:
      path: /root/drone/node-zzf/next_cache
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir $HOME/.ssh
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git init
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1
      - git checkout origin/$DRONE_COMMIT_BRANCH -ft
  - name: build
    image: hub.oocc.es/home/pnpm:16
    depends_on:
      - clone
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: next_cache
        path: /drone/src/.next/cache
    commands:
      - pnpm install
      - npm run build
  - name: build_docker
    image: plugins/docker
    environment:
      API_KEY:
        from_secret: api_key
    depends_on:
      - build
    pull: if-not-exists
    settings:
      registry: hub.oocc.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.oocc.es/home/blog
      tags: ${DRONE_COMMIT=latest}${DRONE_BUILD_NUMBER}
  - name: oss
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-aliyun-oss
    depends_on:
      - build
    settings:
      endpoint:
        from_secret: endpoint
      ACCESS_KEY_ID:
        from_secret: accessKeyID
      ACCESS_KEY_SECRET:
        from_secret: accessKeySecret
      BUCKET_NAME:
        from_secret: bucketName
      target: zzf/_next/static
      source: .next/static
  - name: ssh
    image: appleboy/drone-ssh
    depends_on:
      - build_docker
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      password:
        from_secret: k8s_password
      port: 22
      command_timeout: 2m
      script:
        - echo ${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
        - kubectl apply -f https://git.oocc.es/oocc/k3s/raw/branch/master/blog.yaml
        - kubectl set image deployment/blog blog=hub.oocc.es/home/blog:${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
trigger:
  branch:
    - main
  event:
    exclude:
      - promote
      - pull_request
