kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: wwma/drone-github-clone
    settings:
      SSH_KEY:
        from_secret: ssh_key
  - name: build
    image: node:lts-alpine
    depends_on:
      - clone
    commands:
      - corepack enable
      - corepack prepare pnpm@latest-8 --activate
      - pnpm config set store-dir .pnpm-store
      - pnpm -v
      - pnpm install
      - pnpm run build
      - pnpm prune --prod
  - name: build_docker
    image: plugins/docker
    environment:
      API_KEY:
        from_secret: api_key
    depends_on:
      - build
    pull: if-not-exists
    settings:
      registry: hub.ccw.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ccw.es/home/blog
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: oss
    image: registry.cn-shanghai.aliyuncs.com/zzf2001/drone-aliyun-oss
    depends_on:
      - build
    settings:
      endpoint:
        from_secret: endpoint
      ACCESS_KEY_ID:
        from_secret: accessKeyID
      ACCESS_KEY_SECRET:
        from_secret: accessKeySecret
      BUCKET_NAME:
        from_secret: bucketName
      target: zzf/_next/static
      source: .next/static
  - name: ssh
    image: appleboy/drone-ssh
    depends_on:
      - build_docker
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      key:
        from_secret: k8s_key
      port: 22
      command_timeout: 2m
      script:
        - echo ${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
        - kubectl apply -f https://git.ccw.es/ccw/yaml/raw/branch/master/blog.yaml
        - kubectl set image deployment/blog blog=hub.ccw.es/home/blog:${DRONE_COMMIT_SHA:0:8}
