import Header from '../components/Header';
import './globals.scss';
import Footer from '../components/Footer';
import { WebVitals } from './_components/WebVitals';

export const metadata = {
  title: 'ccw.blog',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='zh' data-color-mode='auto' data-dark-theme='dark' data-light-theme='light'>
      <body className='container mx-auto px-3'>
        <WebVitals />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
